package org.jinyuanjava.litemall.db.domain;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class LitemallPromotionGoodsRuleUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table litemall_promotion_goods_rule_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean NOT_DELETED = false;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table litemall_promotion_goods_rule_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean IS_DELETED = true;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_promotion_goods_rule_user.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_promotion_goods_rule_user.rule_id
     *
     * @mbg.generated
     */
    private Integer ruleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_promotion_goods_rule_user.user_class_attr1_code
     *
     * @mbg.generated
     */
    private String userClassAttr1Code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_promotion_goods_rule_user.user_class_attr1_name
     *
     * @mbg.generated
     */
    private String userClassAttr1Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_promotion_goods_rule_user.user_class_attr2_code
     *
     * @mbg.generated
     */
    private String userClassAttr2Code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_promotion_goods_rule_user.user_class_attr2_name
     *
     * @mbg.generated
     */
    private String userClassAttr2Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_promotion_goods_rule_user.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_promotion_goods_rule_user.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_promotion_goods_rule_user.goods_count
     *
     * @mbg.generated
     */
    private Integer goodsCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_promotion_goods_rule_user.user_nickname
     *
     * @mbg.generated
     */
    private String userNickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_promotion_goods_rule_user.crm_id
     *
     * @mbg.generated
     */
    private String crmId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_promotion_goods_rule_user.add_time
     *
     * @mbg.generated
     */
    private LocalDateTime addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_promotion_goods_rule_user.update_time
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_promotion_goods_rule_user.deleted
     *
     * @mbg.generated
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_promotion_goods_rule_user.id
     *
     * @return the value of litemall_promotion_goods_rule_user.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_promotion_goods_rule_user.id
     *
     * @param id the value for litemall_promotion_goods_rule_user.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_promotion_goods_rule_user.rule_id
     *
     * @return the value of litemall_promotion_goods_rule_user.rule_id
     *
     * @mbg.generated
     */
    public Integer getRuleId() {
        return ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_promotion_goods_rule_user.rule_id
     *
     * @param ruleId the value for litemall_promotion_goods_rule_user.rule_id
     *
     * @mbg.generated
     */
    public void setRuleId(Integer ruleId) {
        this.ruleId = ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_promotion_goods_rule_user.user_class_attr1_code
     *
     * @return the value of litemall_promotion_goods_rule_user.user_class_attr1_code
     *
     * @mbg.generated
     */
    public String getUserClassAttr1Code() {
        return userClassAttr1Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_promotion_goods_rule_user.user_class_attr1_code
     *
     * @param userClassAttr1Code the value for litemall_promotion_goods_rule_user.user_class_attr1_code
     *
     * @mbg.generated
     */
    public void setUserClassAttr1Code(String userClassAttr1Code) {
        this.userClassAttr1Code = userClassAttr1Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_promotion_goods_rule_user.user_class_attr1_name
     *
     * @return the value of litemall_promotion_goods_rule_user.user_class_attr1_name
     *
     * @mbg.generated
     */
    public String getUserClassAttr1Name() {
        return userClassAttr1Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_promotion_goods_rule_user.user_class_attr1_name
     *
     * @param userClassAttr1Name the value for litemall_promotion_goods_rule_user.user_class_attr1_name
     *
     * @mbg.generated
     */
    public void setUserClassAttr1Name(String userClassAttr1Name) {
        this.userClassAttr1Name = userClassAttr1Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_promotion_goods_rule_user.user_class_attr2_code
     *
     * @return the value of litemall_promotion_goods_rule_user.user_class_attr2_code
     *
     * @mbg.generated
     */
    public String getUserClassAttr2Code() {
        return userClassAttr2Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_promotion_goods_rule_user.user_class_attr2_code
     *
     * @param userClassAttr2Code the value for litemall_promotion_goods_rule_user.user_class_attr2_code
     *
     * @mbg.generated
     */
    public void setUserClassAttr2Code(String userClassAttr2Code) {
        this.userClassAttr2Code = userClassAttr2Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_promotion_goods_rule_user.user_class_attr2_name
     *
     * @return the value of litemall_promotion_goods_rule_user.user_class_attr2_name
     *
     * @mbg.generated
     */
    public String getUserClassAttr2Name() {
        return userClassAttr2Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_promotion_goods_rule_user.user_class_attr2_name
     *
     * @param userClassAttr2Name the value for litemall_promotion_goods_rule_user.user_class_attr2_name
     *
     * @mbg.generated
     */
    public void setUserClassAttr2Name(String userClassAttr2Name) {
        this.userClassAttr2Name = userClassAttr2Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_promotion_goods_rule_user.user_id
     *
     * @return the value of litemall_promotion_goods_rule_user.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_promotion_goods_rule_user.user_id
     *
     * @param userId the value for litemall_promotion_goods_rule_user.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_promotion_goods_rule_user.username
     *
     * @return the value of litemall_promotion_goods_rule_user.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_promotion_goods_rule_user.username
     *
     * @param username the value for litemall_promotion_goods_rule_user.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_promotion_goods_rule_user.goods_count
     *
     * @return the value of litemall_promotion_goods_rule_user.goods_count
     *
     * @mbg.generated
     */
    public Integer getGoodsCount() {
        return goodsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_promotion_goods_rule_user.goods_count
     *
     * @param goodsCount the value for litemall_promotion_goods_rule_user.goods_count
     *
     * @mbg.generated
     */
    public void setGoodsCount(Integer goodsCount) {
        this.goodsCount = goodsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_promotion_goods_rule_user.user_nickname
     *
     * @return the value of litemall_promotion_goods_rule_user.user_nickname
     *
     * @mbg.generated
     */
    public String getUserNickname() {
        return userNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_promotion_goods_rule_user.user_nickname
     *
     * @param userNickname the value for litemall_promotion_goods_rule_user.user_nickname
     *
     * @mbg.generated
     */
    public void setUserNickname(String userNickname) {
        this.userNickname = userNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_promotion_goods_rule_user.crm_id
     *
     * @return the value of litemall_promotion_goods_rule_user.crm_id
     *
     * @mbg.generated
     */
    public String getCrmId() {
        return crmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_promotion_goods_rule_user.crm_id
     *
     * @param crmId the value for litemall_promotion_goods_rule_user.crm_id
     *
     * @mbg.generated
     */
    public void setCrmId(String crmId) {
        this.crmId = crmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_promotion_goods_rule_user.add_time
     *
     * @return the value of litemall_promotion_goods_rule_user.add_time
     *
     * @mbg.generated
     */
    public LocalDateTime getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_promotion_goods_rule_user.add_time
     *
     * @param addTime the value for litemall_promotion_goods_rule_user.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(LocalDateTime addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_promotion_goods_rule_user.update_time
     *
     * @return the value of litemall_promotion_goods_rule_user.update_time
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_promotion_goods_rule_user.update_time
     *
     * @param updateTime the value for litemall_promotion_goods_rule_user.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_promotion_goods_rule_user.deleted
     *
     * @return the value of litemall_promotion_goods_rule_user.deleted
     *
     * @mbg.generated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_promotion_goods_rule_user.deleted
     *
     * @param deleted the value for litemall_promotion_goods_rule_user.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_promotion_goods_rule_user
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", ruleId=").append(ruleId);
        sb.append(", userClassAttr1Code=").append(userClassAttr1Code);
        sb.append(", userClassAttr1Name=").append(userClassAttr1Name);
        sb.append(", userClassAttr2Code=").append(userClassAttr2Code);
        sb.append(", userClassAttr2Name=").append(userClassAttr2Name);
        sb.append(", userId=").append(userId);
        sb.append(", username=").append(username);
        sb.append(", goodsCount=").append(goodsCount);
        sb.append(", userNickname=").append(userNickname);
        sb.append(", crmId=").append(crmId);
        sb.append(", addTime=").append(addTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", deleted=").append(deleted);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_promotion_goods_rule_user
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        LitemallPromotionGoodsRuleUser other = (LitemallPromotionGoodsRuleUser) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getRuleId() == null ? other.getRuleId() == null : this.getRuleId().equals(other.getRuleId()))
            && (this.getUserClassAttr1Code() == null ? other.getUserClassAttr1Code() == null : this.getUserClassAttr1Code().equals(other.getUserClassAttr1Code()))
            && (this.getUserClassAttr1Name() == null ? other.getUserClassAttr1Name() == null : this.getUserClassAttr1Name().equals(other.getUserClassAttr1Name()))
            && (this.getUserClassAttr2Code() == null ? other.getUserClassAttr2Code() == null : this.getUserClassAttr2Code().equals(other.getUserClassAttr2Code()))
            && (this.getUserClassAttr2Name() == null ? other.getUserClassAttr2Name() == null : this.getUserClassAttr2Name().equals(other.getUserClassAttr2Name()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getUsername() == null ? other.getUsername() == null : this.getUsername().equals(other.getUsername()))
            && (this.getGoodsCount() == null ? other.getGoodsCount() == null : this.getGoodsCount().equals(other.getGoodsCount()))
            && (this.getUserNickname() == null ? other.getUserNickname() == null : this.getUserNickname().equals(other.getUserNickname()))
            && (this.getCrmId() == null ? other.getCrmId() == null : this.getCrmId().equals(other.getCrmId()))
            && (this.getAddTime() == null ? other.getAddTime() == null : this.getAddTime().equals(other.getAddTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getDeleted() == null ? other.getDeleted() == null : this.getDeleted().equals(other.getDeleted()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_promotion_goods_rule_user
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getRuleId() == null) ? 0 : getRuleId().hashCode());
        result = prime * result + ((getUserClassAttr1Code() == null) ? 0 : getUserClassAttr1Code().hashCode());
        result = prime * result + ((getUserClassAttr1Name() == null) ? 0 : getUserClassAttr1Name().hashCode());
        result = prime * result + ((getUserClassAttr2Code() == null) ? 0 : getUserClassAttr2Code().hashCode());
        result = prime * result + ((getUserClassAttr2Name() == null) ? 0 : getUserClassAttr2Name().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getUsername() == null) ? 0 : getUsername().hashCode());
        result = prime * result + ((getGoodsCount() == null) ? 0 : getGoodsCount().hashCode());
        result = prime * result + ((getUserNickname() == null) ? 0 : getUserNickname().hashCode());
        result = prime * result + ((getCrmId() == null) ? 0 : getCrmId().hashCode());
        result = prime * result + ((getAddTime() == null) ? 0 : getAddTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getDeleted() == null) ? 0 : getDeleted().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_promotion_goods_rule_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void andLogicalDeleted(boolean deleted) {
        setDeleted(deleted ? IS_DELETED : NOT_DELETED);
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table litemall_promotion_goods_rule_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        ruleId("rule_id", "ruleId", "INTEGER", false),
        userClassAttr1Code("user_class_attr1_code", "userClassAttr1Code", "VARCHAR", false),
        userClassAttr1Name("user_class_attr1_name", "userClassAttr1Name", "VARCHAR", false),
        userClassAttr2Code("user_class_attr2_code", "userClassAttr2Code", "VARCHAR", false),
        userClassAttr2Name("user_class_attr2_name", "userClassAttr2Name", "VARCHAR", false),
        userId("user_id", "userId", "INTEGER", false),
        username("username", "username", "VARCHAR", false),
        goodsCount("goods_count", "goodsCount", "INTEGER", false),
        userNickname("user_nickname", "userNickname", "VARCHAR", false),
        crmId("crm_id", "crmId", "VARCHAR", false),
        addTime("add_time", "addTime", "TIMESTAMP", false),
        updateTime("update_time", "updateTime", "TIMESTAMP", false),
        deleted("deleted", "deleted", "BIT", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_promotion_goods_rule_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_promotion_goods_rule_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_promotion_goods_rule_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_promotion_goods_rule_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_promotion_goods_rule_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_promotion_goods_rule_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_promotion_goods_rule_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_promotion_goods_rule_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_promotion_goods_rule_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_promotion_goods_rule_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_promotion_goods_rule_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_promotion_goods_rule_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_promotion_goods_rule_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_promotion_goods_rule_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_promotion_goods_rule_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }
    }
}