package org.jinyuanjava.litemall.db.domain;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class LitemallGrouponRules {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table litemall_groupon_rules
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean NOT_DELETED = false;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table litemall_groupon_rules
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean IS_DELETED = true;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_groupon_rules.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_groupon_rules.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_groupon_rules.com_id
     *
     * @mbg.generated
     */
    private Integer comId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_groupon_rules.com_name
     *
     * @mbg.generated
     */
    private String comName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_groupon_rules.goods_id
     *
     * @mbg.generated
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_groupon_rules.goods_sn
     *
     * @mbg.generated
     */
    private String goodsSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_groupon_rules.goods_name
     *
     * @mbg.generated
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_groupon_rules.goods_product_id
     *
     * @mbg.generated
     */
    private Integer goodsProductId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_groupon_rules.goods_product_specifications
     *
     * @mbg.generated
     */
    private String[] goodsProductSpecifications;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_groupon_rules.source_price
     *
     * @mbg.generated
     */
    private BigDecimal sourcePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_groupon_rules.groupon_price
     *
     * @mbg.generated
     */
    private BigDecimal grouponPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_groupon_rules.group_minperson
     *
     * @mbg.generated
     */
    private Integer groupMinperson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_groupon_rules.group_max_store
     *
     * @mbg.generated
     */
    private Integer groupMaxStore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_groupon_rules.group_remain_store
     *
     * @mbg.generated
     */
    private Integer groupRemainStore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_groupon_rules.un_pay_num
     *
     * @mbg.generated
     */
    private Integer unPayNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_groupon_rules.have_pay_num
     *
     * @mbg.generated
     */
    private Integer havePayNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_groupon_rules.begin_date
     *
     * @mbg.generated
     */
    private LocalDateTime beginDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_groupon_rules.expire_time
     *
     * @mbg.generated
     */
    private LocalDateTime expireTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_groupon_rules.expire_flag
     *
     * @mbg.generated
     */
    private Boolean expireFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_groupon_rules.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_groupon_rules.pic_url
     *
     * @mbg.generated
     */
    private String picUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_groupon_rules.free_post
     *
     * @mbg.generated
     */
    private Boolean freePost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_groupon_rules.if_use_coupon
     *
     * @mbg.generated
     */
    private Boolean ifUseCoupon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_groupon_rules.if_use_bonus
     *
     * @mbg.generated
     */
    private Boolean ifUseBonus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_groupon_rules.add_time
     *
     * @mbg.generated
     */
    private LocalDateTime addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_groupon_rules.update_time
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_groupon_rules.deleted
     *
     * @mbg.generated
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_groupon_rules.id
     *
     * @return the value of litemall_groupon_rules.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_groupon_rules.id
     *
     * @param id the value for litemall_groupon_rules.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_groupon_rules.name
     *
     * @return the value of litemall_groupon_rules.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_groupon_rules.name
     *
     * @param name the value for litemall_groupon_rules.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_groupon_rules.com_id
     *
     * @return the value of litemall_groupon_rules.com_id
     *
     * @mbg.generated
     */
    public Integer getComId() {
        return comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_groupon_rules.com_id
     *
     * @param comId the value for litemall_groupon_rules.com_id
     *
     * @mbg.generated
     */
    public void setComId(Integer comId) {
        this.comId = comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_groupon_rules.com_name
     *
     * @return the value of litemall_groupon_rules.com_name
     *
     * @mbg.generated
     */
    public String getComName() {
        return comName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_groupon_rules.com_name
     *
     * @param comName the value for litemall_groupon_rules.com_name
     *
     * @mbg.generated
     */
    public void setComName(String comName) {
        this.comName = comName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_groupon_rules.goods_id
     *
     * @return the value of litemall_groupon_rules.goods_id
     *
     * @mbg.generated
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_groupon_rules.goods_id
     *
     * @param goodsId the value for litemall_groupon_rules.goods_id
     *
     * @mbg.generated
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_groupon_rules.goods_sn
     *
     * @return the value of litemall_groupon_rules.goods_sn
     *
     * @mbg.generated
     */
    public String getGoodsSn() {
        return goodsSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_groupon_rules.goods_sn
     *
     * @param goodsSn the value for litemall_groupon_rules.goods_sn
     *
     * @mbg.generated
     */
    public void setGoodsSn(String goodsSn) {
        this.goodsSn = goodsSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_groupon_rules.goods_name
     *
     * @return the value of litemall_groupon_rules.goods_name
     *
     * @mbg.generated
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_groupon_rules.goods_name
     *
     * @param goodsName the value for litemall_groupon_rules.goods_name
     *
     * @mbg.generated
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_groupon_rules.goods_product_id
     *
     * @return the value of litemall_groupon_rules.goods_product_id
     *
     * @mbg.generated
     */
    public Integer getGoodsProductId() {
        return goodsProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_groupon_rules.goods_product_id
     *
     * @param goodsProductId the value for litemall_groupon_rules.goods_product_id
     *
     * @mbg.generated
     */
    public void setGoodsProductId(Integer goodsProductId) {
        this.goodsProductId = goodsProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_groupon_rules.goods_product_specifications
     *
     * @return the value of litemall_groupon_rules.goods_product_specifications
     *
     * @mbg.generated
     */
    public String[] getGoodsProductSpecifications() {
        return goodsProductSpecifications;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_groupon_rules.goods_product_specifications
     *
     * @param goodsProductSpecifications the value for litemall_groupon_rules.goods_product_specifications
     *
     * @mbg.generated
     */
    public void setGoodsProductSpecifications(String[] goodsProductSpecifications) {
        this.goodsProductSpecifications = goodsProductSpecifications;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_groupon_rules.source_price
     *
     * @return the value of litemall_groupon_rules.source_price
     *
     * @mbg.generated
     */
    public BigDecimal getSourcePrice() {
        return sourcePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_groupon_rules.source_price
     *
     * @param sourcePrice the value for litemall_groupon_rules.source_price
     *
     * @mbg.generated
     */
    public void setSourcePrice(BigDecimal sourcePrice) {
        this.sourcePrice = sourcePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_groupon_rules.groupon_price
     *
     * @return the value of litemall_groupon_rules.groupon_price
     *
     * @mbg.generated
     */
    public BigDecimal getGrouponPrice() {
        return grouponPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_groupon_rules.groupon_price
     *
     * @param grouponPrice the value for litemall_groupon_rules.groupon_price
     *
     * @mbg.generated
     */
    public void setGrouponPrice(BigDecimal grouponPrice) {
        this.grouponPrice = grouponPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_groupon_rules.group_minperson
     *
     * @return the value of litemall_groupon_rules.group_minperson
     *
     * @mbg.generated
     */
    public Integer getGroupMinperson() {
        return groupMinperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_groupon_rules.group_minperson
     *
     * @param groupMinperson the value for litemall_groupon_rules.group_minperson
     *
     * @mbg.generated
     */
    public void setGroupMinperson(Integer groupMinperson) {
        this.groupMinperson = groupMinperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_groupon_rules.group_max_store
     *
     * @return the value of litemall_groupon_rules.group_max_store
     *
     * @mbg.generated
     */
    public Integer getGroupMaxStore() {
        return groupMaxStore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_groupon_rules.group_max_store
     *
     * @param groupMaxStore the value for litemall_groupon_rules.group_max_store
     *
     * @mbg.generated
     */
    public void setGroupMaxStore(Integer groupMaxStore) {
        this.groupMaxStore = groupMaxStore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_groupon_rules.group_remain_store
     *
     * @return the value of litemall_groupon_rules.group_remain_store
     *
     * @mbg.generated
     */
    public Integer getGroupRemainStore() {
        return groupRemainStore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_groupon_rules.group_remain_store
     *
     * @param groupRemainStore the value for litemall_groupon_rules.group_remain_store
     *
     * @mbg.generated
     */
    public void setGroupRemainStore(Integer groupRemainStore) {
        this.groupRemainStore = groupRemainStore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_groupon_rules.un_pay_num
     *
     * @return the value of litemall_groupon_rules.un_pay_num
     *
     * @mbg.generated
     */
    public Integer getUnPayNum() {
        return unPayNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_groupon_rules.un_pay_num
     *
     * @param unPayNum the value for litemall_groupon_rules.un_pay_num
     *
     * @mbg.generated
     */
    public void setUnPayNum(Integer unPayNum) {
        this.unPayNum = unPayNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_groupon_rules.have_pay_num
     *
     * @return the value of litemall_groupon_rules.have_pay_num
     *
     * @mbg.generated
     */
    public Integer getHavePayNum() {
        return havePayNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_groupon_rules.have_pay_num
     *
     * @param havePayNum the value for litemall_groupon_rules.have_pay_num
     *
     * @mbg.generated
     */
    public void setHavePayNum(Integer havePayNum) {
        this.havePayNum = havePayNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_groupon_rules.begin_date
     *
     * @return the value of litemall_groupon_rules.begin_date
     *
     * @mbg.generated
     */
    public LocalDateTime getBeginDate() {
        return beginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_groupon_rules.begin_date
     *
     * @param beginDate the value for litemall_groupon_rules.begin_date
     *
     * @mbg.generated
     */
    public void setBeginDate(LocalDateTime beginDate) {
        this.beginDate = beginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_groupon_rules.expire_time
     *
     * @return the value of litemall_groupon_rules.expire_time
     *
     * @mbg.generated
     */
    public LocalDateTime getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_groupon_rules.expire_time
     *
     * @param expireTime the value for litemall_groupon_rules.expire_time
     *
     * @mbg.generated
     */
    public void setExpireTime(LocalDateTime expireTime) {
        this.expireTime = expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_groupon_rules.expire_flag
     *
     * @return the value of litemall_groupon_rules.expire_flag
     *
     * @mbg.generated
     */
    public Boolean getExpireFlag() {
        return expireFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_groupon_rules.expire_flag
     *
     * @param expireFlag the value for litemall_groupon_rules.expire_flag
     *
     * @mbg.generated
     */
    public void setExpireFlag(Boolean expireFlag) {
        this.expireFlag = expireFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_groupon_rules.remark
     *
     * @return the value of litemall_groupon_rules.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_groupon_rules.remark
     *
     * @param remark the value for litemall_groupon_rules.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_groupon_rules.pic_url
     *
     * @return the value of litemall_groupon_rules.pic_url
     *
     * @mbg.generated
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_groupon_rules.pic_url
     *
     * @param picUrl the value for litemall_groupon_rules.pic_url
     *
     * @mbg.generated
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_groupon_rules.free_post
     *
     * @return the value of litemall_groupon_rules.free_post
     *
     * @mbg.generated
     */
    public Boolean getFreePost() {
        return freePost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_groupon_rules.free_post
     *
     * @param freePost the value for litemall_groupon_rules.free_post
     *
     * @mbg.generated
     */
    public void setFreePost(Boolean freePost) {
        this.freePost = freePost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_groupon_rules.if_use_coupon
     *
     * @return the value of litemall_groupon_rules.if_use_coupon
     *
     * @mbg.generated
     */
    public Boolean getIfUseCoupon() {
        return ifUseCoupon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_groupon_rules.if_use_coupon
     *
     * @param ifUseCoupon the value for litemall_groupon_rules.if_use_coupon
     *
     * @mbg.generated
     */
    public void setIfUseCoupon(Boolean ifUseCoupon) {
        this.ifUseCoupon = ifUseCoupon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_groupon_rules.if_use_bonus
     *
     * @return the value of litemall_groupon_rules.if_use_bonus
     *
     * @mbg.generated
     */
    public Boolean getIfUseBonus() {
        return ifUseBonus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_groupon_rules.if_use_bonus
     *
     * @param ifUseBonus the value for litemall_groupon_rules.if_use_bonus
     *
     * @mbg.generated
     */
    public void setIfUseBonus(Boolean ifUseBonus) {
        this.ifUseBonus = ifUseBonus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_groupon_rules.add_time
     *
     * @return the value of litemall_groupon_rules.add_time
     *
     * @mbg.generated
     */
    public LocalDateTime getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_groupon_rules.add_time
     *
     * @param addTime the value for litemall_groupon_rules.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(LocalDateTime addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_groupon_rules.update_time
     *
     * @return the value of litemall_groupon_rules.update_time
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_groupon_rules.update_time
     *
     * @param updateTime the value for litemall_groupon_rules.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_groupon_rules.deleted
     *
     * @return the value of litemall_groupon_rules.deleted
     *
     * @mbg.generated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_groupon_rules.deleted
     *
     * @param deleted the value for litemall_groupon_rules.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_groupon_rules
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", comId=").append(comId);
        sb.append(", comName=").append(comName);
        sb.append(", goodsId=").append(goodsId);
        sb.append(", goodsSn=").append(goodsSn);
        sb.append(", goodsName=").append(goodsName);
        sb.append(", goodsProductId=").append(goodsProductId);
        sb.append(", goodsProductSpecifications=").append(goodsProductSpecifications);
        sb.append(", sourcePrice=").append(sourcePrice);
        sb.append(", grouponPrice=").append(grouponPrice);
        sb.append(", groupMinperson=").append(groupMinperson);
        sb.append(", groupMaxStore=").append(groupMaxStore);
        sb.append(", groupRemainStore=").append(groupRemainStore);
        sb.append(", unPayNum=").append(unPayNum);
        sb.append(", havePayNum=").append(havePayNum);
        sb.append(", beginDate=").append(beginDate);
        sb.append(", expireTime=").append(expireTime);
        sb.append(", expireFlag=").append(expireFlag);
        sb.append(", remark=").append(remark);
        sb.append(", picUrl=").append(picUrl);
        sb.append(", freePost=").append(freePost);
        sb.append(", ifUseCoupon=").append(ifUseCoupon);
        sb.append(", ifUseBonus=").append(ifUseBonus);
        sb.append(", addTime=").append(addTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", deleted=").append(deleted);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_groupon_rules
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        LitemallGrouponRules other = (LitemallGrouponRules) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getComId() == null ? other.getComId() == null : this.getComId().equals(other.getComId()))
            && (this.getComName() == null ? other.getComName() == null : this.getComName().equals(other.getComName()))
            && (this.getGoodsId() == null ? other.getGoodsId() == null : this.getGoodsId().equals(other.getGoodsId()))
            && (this.getGoodsSn() == null ? other.getGoodsSn() == null : this.getGoodsSn().equals(other.getGoodsSn()))
            && (this.getGoodsName() == null ? other.getGoodsName() == null : this.getGoodsName().equals(other.getGoodsName()))
            && (this.getGoodsProductId() == null ? other.getGoodsProductId() == null : this.getGoodsProductId().equals(other.getGoodsProductId()))
            && (Arrays.equals(this.getGoodsProductSpecifications(), other.getGoodsProductSpecifications()))
            && (this.getSourcePrice() == null ? other.getSourcePrice() == null : this.getSourcePrice().equals(other.getSourcePrice()))
            && (this.getGrouponPrice() == null ? other.getGrouponPrice() == null : this.getGrouponPrice().equals(other.getGrouponPrice()))
            && (this.getGroupMinperson() == null ? other.getGroupMinperson() == null : this.getGroupMinperson().equals(other.getGroupMinperson()))
            && (this.getGroupMaxStore() == null ? other.getGroupMaxStore() == null : this.getGroupMaxStore().equals(other.getGroupMaxStore()))
            && (this.getGroupRemainStore() == null ? other.getGroupRemainStore() == null : this.getGroupRemainStore().equals(other.getGroupRemainStore()))
            && (this.getUnPayNum() == null ? other.getUnPayNum() == null : this.getUnPayNum().equals(other.getUnPayNum()))
            && (this.getHavePayNum() == null ? other.getHavePayNum() == null : this.getHavePayNum().equals(other.getHavePayNum()))
            && (this.getBeginDate() == null ? other.getBeginDate() == null : this.getBeginDate().equals(other.getBeginDate()))
            && (this.getExpireTime() == null ? other.getExpireTime() == null : this.getExpireTime().equals(other.getExpireTime()))
            && (this.getExpireFlag() == null ? other.getExpireFlag() == null : this.getExpireFlag().equals(other.getExpireFlag()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
            && (this.getPicUrl() == null ? other.getPicUrl() == null : this.getPicUrl().equals(other.getPicUrl()))
            && (this.getFreePost() == null ? other.getFreePost() == null : this.getFreePost().equals(other.getFreePost()))
            && (this.getIfUseCoupon() == null ? other.getIfUseCoupon() == null : this.getIfUseCoupon().equals(other.getIfUseCoupon()))
            && (this.getIfUseBonus() == null ? other.getIfUseBonus() == null : this.getIfUseBonus().equals(other.getIfUseBonus()))
            && (this.getAddTime() == null ? other.getAddTime() == null : this.getAddTime().equals(other.getAddTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getDeleted() == null ? other.getDeleted() == null : this.getDeleted().equals(other.getDeleted()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_groupon_rules
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getComId() == null) ? 0 : getComId().hashCode());
        result = prime * result + ((getComName() == null) ? 0 : getComName().hashCode());
        result = prime * result + ((getGoodsId() == null) ? 0 : getGoodsId().hashCode());
        result = prime * result + ((getGoodsSn() == null) ? 0 : getGoodsSn().hashCode());
        result = prime * result + ((getGoodsName() == null) ? 0 : getGoodsName().hashCode());
        result = prime * result + ((getGoodsProductId() == null) ? 0 : getGoodsProductId().hashCode());
        result = prime * result + (Arrays.hashCode(getGoodsProductSpecifications()));
        result = prime * result + ((getSourcePrice() == null) ? 0 : getSourcePrice().hashCode());
        result = prime * result + ((getGrouponPrice() == null) ? 0 : getGrouponPrice().hashCode());
        result = prime * result + ((getGroupMinperson() == null) ? 0 : getGroupMinperson().hashCode());
        result = prime * result + ((getGroupMaxStore() == null) ? 0 : getGroupMaxStore().hashCode());
        result = prime * result + ((getGroupRemainStore() == null) ? 0 : getGroupRemainStore().hashCode());
        result = prime * result + ((getUnPayNum() == null) ? 0 : getUnPayNum().hashCode());
        result = prime * result + ((getHavePayNum() == null) ? 0 : getHavePayNum().hashCode());
        result = prime * result + ((getBeginDate() == null) ? 0 : getBeginDate().hashCode());
        result = prime * result + ((getExpireTime() == null) ? 0 : getExpireTime().hashCode());
        result = prime * result + ((getExpireFlag() == null) ? 0 : getExpireFlag().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getPicUrl() == null) ? 0 : getPicUrl().hashCode());
        result = prime * result + ((getFreePost() == null) ? 0 : getFreePost().hashCode());
        result = prime * result + ((getIfUseCoupon() == null) ? 0 : getIfUseCoupon().hashCode());
        result = prime * result + ((getIfUseBonus() == null) ? 0 : getIfUseBonus().hashCode());
        result = prime * result + ((getAddTime() == null) ? 0 : getAddTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getDeleted() == null) ? 0 : getDeleted().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_groupon_rules
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void andLogicalDeleted(boolean deleted) {
        setDeleted(deleted ? IS_DELETED : NOT_DELETED);
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table litemall_groupon_rules
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        name("name", "name", "VARCHAR", true),
        comId("com_id", "comId", "INTEGER", false),
        comName("com_name", "comName", "VARCHAR", false),
        goodsId("goods_id", "goodsId", "INTEGER", false),
        goodsSn("goods_sn", "goodsSn", "VARCHAR", false),
        goodsName("goods_name", "goodsName", "VARCHAR", false),
        goodsProductId("goods_product_id", "goodsProductId", "INTEGER", false),
        goodsProductSpecifications("goods_product_specifications", "goodsProductSpecifications", "VARCHAR", false),
        sourcePrice("source_price", "sourcePrice", "DECIMAL", false),
        grouponPrice("groupon_price", "grouponPrice", "DECIMAL", false),
        groupMinperson("group_minperson", "groupMinperson", "INTEGER", false),
        groupMaxStore("group_max_store", "groupMaxStore", "INTEGER", false),
        groupRemainStore("group_remain_store", "groupRemainStore", "INTEGER", false),
        unPayNum("un_pay_num", "unPayNum", "INTEGER", false),
        havePayNum("have_pay_num", "havePayNum", "INTEGER", false),
        beginDate("begin_date", "beginDate", "TIMESTAMP", false),
        expireTime("expire_time", "expireTime", "TIMESTAMP", false),
        expireFlag("expire_flag", "expireFlag", "BIT", false),
        remark("remark", "remark", "VARCHAR", false),
        picUrl("pic_url", "picUrl", "VARCHAR", false),
        freePost("free_post", "freePost", "BIT", false),
        ifUseCoupon("if_use_coupon", "ifUseCoupon", "BIT", false),
        ifUseBonus("if_use_bonus", "ifUseBonus", "BIT", false),
        addTime("add_time", "addTime", "TIMESTAMP", false),
        updateTime("update_time", "updateTime", "TIMESTAMP", false),
        deleted("deleted", "deleted", "BIT", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_groupon_rules
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_groupon_rules
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_groupon_rules
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_groupon_rules
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_groupon_rules
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_groupon_rules
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_groupon_rules
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_groupon_rules
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_groupon_rules
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_groupon_rules
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_groupon_rules
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_groupon_rules
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_groupon_rules
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_groupon_rules
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_groupon_rules
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }
    }
}