package org.jinyuanjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.jinyuanjava.litemall.db.domain.LitemallUserOrderInfo;
import org.jinyuanjava.litemall.db.domain.LitemallUserOrderInfoExample;

public interface LitemallUserOrderInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_order_info
     *
     * @mbg.generated
     */
    long countByExample(LitemallUserOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_order_info
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallUserOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_order_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_order_info
     *
     * @mbg.generated
     */
    int insert(LitemallUserOrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_order_info
     *
     * @mbg.generated
     */
    int insertSelective(LitemallUserOrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_order_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallUserOrderInfo selectOneByExample(LitemallUserOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_order_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallUserOrderInfo selectOneByExampleSelective(@Param("example") LitemallUserOrderInfoExample example, @Param("selective") LitemallUserOrderInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_order_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallUserOrderInfo> selectByExampleSelective(@Param("example") LitemallUserOrderInfoExample example, @Param("selective") LitemallUserOrderInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_order_info
     *
     * @mbg.generated
     */
    List<LitemallUserOrderInfo> selectByExample(LitemallUserOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_order_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallUserOrderInfo selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallUserOrderInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_order_info
     *
     * @mbg.generated
     */
    LitemallUserOrderInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_order_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallUserOrderInfo selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_order_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallUserOrderInfo record, @Param("example") LitemallUserOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_order_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallUserOrderInfo record, @Param("example") LitemallUserOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_order_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallUserOrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_order_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallUserOrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_order_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") LitemallUserOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_order_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}