package org.jinyuanjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.jinyuanjava.litemall.db.domain.LitemallAuthororcorpPara;
import org.jinyuanjava.litemall.db.domain.LitemallAuthororcorpParaExample;

public interface LitemallAuthororcorpParaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_authororcorp_para
     *
     * @mbg.generated
     */
    long countByExample(LitemallAuthororcorpParaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_authororcorp_para
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallAuthororcorpParaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_authororcorp_para
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_authororcorp_para
     *
     * @mbg.generated
     */
    int insert(LitemallAuthororcorpPara record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_authororcorp_para
     *
     * @mbg.generated
     */
    int insertSelective(LitemallAuthororcorpPara record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_authororcorp_para
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallAuthororcorpPara selectOneByExample(LitemallAuthororcorpParaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_authororcorp_para
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallAuthororcorpPara selectOneByExampleSelective(@Param("example") LitemallAuthororcorpParaExample example, @Param("selective") LitemallAuthororcorpPara.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_authororcorp_para
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallAuthororcorpPara> selectByExampleSelective(@Param("example") LitemallAuthororcorpParaExample example, @Param("selective") LitemallAuthororcorpPara.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_authororcorp_para
     *
     * @mbg.generated
     */
    List<LitemallAuthororcorpPara> selectByExample(LitemallAuthororcorpParaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_authororcorp_para
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallAuthororcorpPara selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallAuthororcorpPara.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_authororcorp_para
     *
     * @mbg.generated
     */
    LitemallAuthororcorpPara selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_authororcorp_para
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallAuthororcorpPara selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_authororcorp_para
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallAuthororcorpPara record, @Param("example") LitemallAuthororcorpParaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_authororcorp_para
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallAuthororcorpPara record, @Param("example") LitemallAuthororcorpParaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_authororcorp_para
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallAuthororcorpPara record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_authororcorp_para
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallAuthororcorpPara record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_authororcorp_para
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") LitemallAuthororcorpParaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_authororcorp_para
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}