package org.jinyuanjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.jinyuanjava.litemall.db.domain.LitemallFapiaoInfo;
import org.jinyuanjava.litemall.db.domain.LitemallFapiaoInfoExample;

public interface LitemallFapiaoInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_fapiao_info
     *
     * @mbg.generated
     */
    long countByExample(LitemallFapiaoInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_fapiao_info
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallFapiaoInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_fapiao_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_fapiao_info
     *
     * @mbg.generated
     */
    int insert(LitemallFapiaoInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_fapiao_info
     *
     * @mbg.generated
     */
    int insertSelective(LitemallFapiaoInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_fapiao_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallFapiaoInfo selectOneByExample(LitemallFapiaoInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_fapiao_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallFapiaoInfo selectOneByExampleSelective(@Param("example") LitemallFapiaoInfoExample example, @Param("selective") LitemallFapiaoInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_fapiao_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallFapiaoInfo> selectByExampleSelective(@Param("example") LitemallFapiaoInfoExample example, @Param("selective") LitemallFapiaoInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_fapiao_info
     *
     * @mbg.generated
     */
    List<LitemallFapiaoInfo> selectByExample(LitemallFapiaoInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_fapiao_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallFapiaoInfo selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallFapiaoInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_fapiao_info
     *
     * @mbg.generated
     */
    LitemallFapiaoInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_fapiao_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallFapiaoInfo selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_fapiao_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallFapiaoInfo record, @Param("example") LitemallFapiaoInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_fapiao_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallFapiaoInfo record, @Param("example") LitemallFapiaoInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_fapiao_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallFapiaoInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_fapiao_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallFapiaoInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_fapiao_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") LitemallFapiaoInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_fapiao_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}