package org.jinyuanjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.jinyuanjava.litemall.db.domain.LitemallAuthororcorpItems;
import org.jinyuanjava.litemall.db.domain.LitemallAuthororcorpItemsExample;

public interface LitemallAuthororcorpItemsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_authororcorp_items
     *
     * @mbg.generated
     */
    long countByExample(LitemallAuthororcorpItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_authororcorp_items
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallAuthororcorpItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_authororcorp_items
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_authororcorp_items
     *
     * @mbg.generated
     */
    int insert(LitemallAuthororcorpItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_authororcorp_items
     *
     * @mbg.generated
     */
    int insertSelective(LitemallAuthororcorpItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_authororcorp_items
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallAuthororcorpItems selectOneByExample(LitemallAuthororcorpItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_authororcorp_items
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallAuthororcorpItems selectOneByExampleSelective(@Param("example") LitemallAuthororcorpItemsExample example, @Param("selective") LitemallAuthororcorpItems.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_authororcorp_items
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallAuthororcorpItems> selectByExampleSelective(@Param("example") LitemallAuthororcorpItemsExample example, @Param("selective") LitemallAuthororcorpItems.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_authororcorp_items
     *
     * @mbg.generated
     */
    List<LitemallAuthororcorpItems> selectByExample(LitemallAuthororcorpItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_authororcorp_items
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallAuthororcorpItems selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallAuthororcorpItems.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_authororcorp_items
     *
     * @mbg.generated
     */
    LitemallAuthororcorpItems selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_authororcorp_items
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallAuthororcorpItems selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_authororcorp_items
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallAuthororcorpItems record, @Param("example") LitemallAuthororcorpItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_authororcorp_items
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallAuthororcorpItems record, @Param("example") LitemallAuthororcorpItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_authororcorp_items
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallAuthororcorpItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_authororcorp_items
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallAuthororcorpItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_authororcorp_items
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") LitemallAuthororcorpItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_authororcorp_items
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}