package org.jinyuanjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.jinyuanjava.litemall.db.domain.LitemallAuctionDajiaOrderCurrent;
import org.jinyuanjava.litemall.db.domain.LitemallAuctionDajiaOrderCurrentExample;

public interface LitemallAuctionDajiaOrderCurrentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_auction_dajia_order_current
     *
     * @mbg.generated
     */
    long countByExample(LitemallAuctionDajiaOrderCurrentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_auction_dajia_order_current
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallAuctionDajiaOrderCurrentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_auction_dajia_order_current
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_auction_dajia_order_current
     *
     * @mbg.generated
     */
    int insert(LitemallAuctionDajiaOrderCurrent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_auction_dajia_order_current
     *
     * @mbg.generated
     */
    int insertSelective(LitemallAuctionDajiaOrderCurrent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_auction_dajia_order_current
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallAuctionDajiaOrderCurrent selectOneByExample(LitemallAuctionDajiaOrderCurrentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_auction_dajia_order_current
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallAuctionDajiaOrderCurrent selectOneByExampleSelective(@Param("example") LitemallAuctionDajiaOrderCurrentExample example, @Param("selective") LitemallAuctionDajiaOrderCurrent.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_auction_dajia_order_current
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallAuctionDajiaOrderCurrent> selectByExampleSelective(@Param("example") LitemallAuctionDajiaOrderCurrentExample example, @Param("selective") LitemallAuctionDajiaOrderCurrent.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_auction_dajia_order_current
     *
     * @mbg.generated
     */
    List<LitemallAuctionDajiaOrderCurrent> selectByExample(LitemallAuctionDajiaOrderCurrentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_auction_dajia_order_current
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallAuctionDajiaOrderCurrent selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallAuctionDajiaOrderCurrent.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_auction_dajia_order_current
     *
     * @mbg.generated
     */
    LitemallAuctionDajiaOrderCurrent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_auction_dajia_order_current
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallAuctionDajiaOrderCurrent selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_auction_dajia_order_current
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallAuctionDajiaOrderCurrent record, @Param("example") LitemallAuctionDajiaOrderCurrentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_auction_dajia_order_current
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallAuctionDajiaOrderCurrent record, @Param("example") LitemallAuctionDajiaOrderCurrentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_auction_dajia_order_current
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallAuctionDajiaOrderCurrent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_auction_dajia_order_current
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallAuctionDajiaOrderCurrent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_auction_dajia_order_current
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") LitemallAuctionDajiaOrderCurrentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_auction_dajia_order_current
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}