package org.jinyuanjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.jinyuanjava.litemall.db.domain.LitemallPromotionGoodsUserOrder;
import org.jinyuanjava.litemall.db.domain.LitemallPromotionGoodsUserOrderExample;

public interface LitemallPromotionGoodsUserOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_promotion_goods_user_order
     *
     * @mbg.generated
     */
    long countByExample(LitemallPromotionGoodsUserOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_promotion_goods_user_order
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallPromotionGoodsUserOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_promotion_goods_user_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_promotion_goods_user_order
     *
     * @mbg.generated
     */
    int insert(LitemallPromotionGoodsUserOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_promotion_goods_user_order
     *
     * @mbg.generated
     */
    int insertSelective(LitemallPromotionGoodsUserOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_promotion_goods_user_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallPromotionGoodsUserOrder selectOneByExample(LitemallPromotionGoodsUserOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_promotion_goods_user_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallPromotionGoodsUserOrder selectOneByExampleSelective(@Param("example") LitemallPromotionGoodsUserOrderExample example, @Param("selective") LitemallPromotionGoodsUserOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_promotion_goods_user_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallPromotionGoodsUserOrder> selectByExampleSelective(@Param("example") LitemallPromotionGoodsUserOrderExample example, @Param("selective") LitemallPromotionGoodsUserOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_promotion_goods_user_order
     *
     * @mbg.generated
     */
    List<LitemallPromotionGoodsUserOrder> selectByExample(LitemallPromotionGoodsUserOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_promotion_goods_user_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallPromotionGoodsUserOrder selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallPromotionGoodsUserOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_promotion_goods_user_order
     *
     * @mbg.generated
     */
    LitemallPromotionGoodsUserOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_promotion_goods_user_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallPromotionGoodsUserOrder selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_promotion_goods_user_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallPromotionGoodsUserOrder record, @Param("example") LitemallPromotionGoodsUserOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_promotion_goods_user_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallPromotionGoodsUserOrder record, @Param("example") LitemallPromotionGoodsUserOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_promotion_goods_user_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallPromotionGoodsUserOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_promotion_goods_user_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallPromotionGoodsUserOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_promotion_goods_user_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") LitemallPromotionGoodsUserOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_promotion_goods_user_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}