package org.jinyuanjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.jinyuanjava.litemall.db.domain.LitemallArticleList;
import org.jinyuanjava.litemall.db.domain.LitemallArticleListExample;

public interface LitemallArticleListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_article_list
     *
     * @mbg.generated
     */
    long countByExample(LitemallArticleListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_article_list
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallArticleListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_article_list
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_article_list
     *
     * @mbg.generated
     */
    int insert(LitemallArticleList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_article_list
     *
     * @mbg.generated
     */
    int insertSelective(LitemallArticleList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_article_list
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallArticleList selectOneByExample(LitemallArticleListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_article_list
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallArticleList selectOneByExampleSelective(@Param("example") LitemallArticleListExample example, @Param("selective") LitemallArticleList.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_article_list
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallArticleList selectOneByExampleWithBLOBs(LitemallArticleListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_article_list
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallArticleList> selectByExampleSelective(@Param("example") LitemallArticleListExample example, @Param("selective") LitemallArticleList.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_article_list
     *
     * @mbg.generated
     */
    List<LitemallArticleList> selectByExampleWithBLOBs(LitemallArticleListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_article_list
     *
     * @mbg.generated
     */
    List<LitemallArticleList> selectByExample(LitemallArticleListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_article_list
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallArticleList selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallArticleList.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_article_list
     *
     * @mbg.generated
     */
    LitemallArticleList selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_article_list
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallArticleList selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_article_list
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallArticleList record, @Param("example") LitemallArticleListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_article_list
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") LitemallArticleList record, @Param("example") LitemallArticleListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_article_list
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallArticleList record, @Param("example") LitemallArticleListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_article_list
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallArticleList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_article_list
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(LitemallArticleList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_article_list
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallArticleList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_article_list
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") LitemallArticleListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_article_list
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}