package org.jinyuanjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.jinyuanjava.litemall.db.domain.LitemallRoleMenu;
import org.jinyuanjava.litemall.db.domain.LitemallRoleMenuExample;

public interface LitemallRoleMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_role_menu
     *
     * @mbg.generated
     */
    long countByExample(LitemallRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_role_menu
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_role_menu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_role_menu
     *
     * @mbg.generated
     */
    int insert(LitemallRoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_role_menu
     *
     * @mbg.generated
     */
    int insertSelective(LitemallRoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_role_menu
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallRoleMenu selectOneByExample(LitemallRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_role_menu
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallRoleMenu selectOneByExampleSelective(@Param("example") LitemallRoleMenuExample example, @Param("selective") LitemallRoleMenu.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_role_menu
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallRoleMenu> selectByExampleSelective(@Param("example") LitemallRoleMenuExample example, @Param("selective") LitemallRoleMenu.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_role_menu
     *
     * @mbg.generated
     */
    List<LitemallRoleMenu> selectByExample(LitemallRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_role_menu
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallRoleMenu selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallRoleMenu.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_role_menu
     *
     * @mbg.generated
     */
    LitemallRoleMenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_role_menu
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallRoleMenu selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_role_menu
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallRoleMenu record, @Param("example") LitemallRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_role_menu
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallRoleMenu record, @Param("example") LitemallRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_role_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallRoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_role_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallRoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_role_menu
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") LitemallRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_role_menu
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}