package org.jinyuanjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.jinyuanjava.litemall.db.domain.LitemallPromotionSeckillRule;
import org.jinyuanjava.litemall.db.domain.LitemallPromotionSeckillRuleExample;

public interface LitemallPromotionSeckillRuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_promotion_seckill_rule
     *
     * @mbg.generated
     */
    long countByExample(LitemallPromotionSeckillRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_promotion_seckill_rule
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallPromotionSeckillRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_promotion_seckill_rule
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_promotion_seckill_rule
     *
     * @mbg.generated
     */
    int insert(LitemallPromotionSeckillRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_promotion_seckill_rule
     *
     * @mbg.generated
     */
    int insertSelective(LitemallPromotionSeckillRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_promotion_seckill_rule
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallPromotionSeckillRule selectOneByExample(LitemallPromotionSeckillRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_promotion_seckill_rule
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallPromotionSeckillRule selectOneByExampleSelective(@Param("example") LitemallPromotionSeckillRuleExample example, @Param("selective") LitemallPromotionSeckillRule.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_promotion_seckill_rule
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallPromotionSeckillRule> selectByExampleSelective(@Param("example") LitemallPromotionSeckillRuleExample example, @Param("selective") LitemallPromotionSeckillRule.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_promotion_seckill_rule
     *
     * @mbg.generated
     */
    List<LitemallPromotionSeckillRule> selectByExample(LitemallPromotionSeckillRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_promotion_seckill_rule
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallPromotionSeckillRule selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallPromotionSeckillRule.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_promotion_seckill_rule
     *
     * @mbg.generated
     */
    LitemallPromotionSeckillRule selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_promotion_seckill_rule
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallPromotionSeckillRule selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_promotion_seckill_rule
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallPromotionSeckillRule record, @Param("example") LitemallPromotionSeckillRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_promotion_seckill_rule
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallPromotionSeckillRule record, @Param("example") LitemallPromotionSeckillRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_promotion_seckill_rule
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallPromotionSeckillRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_promotion_seckill_rule
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallPromotionSeckillRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_promotion_seckill_rule
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") LitemallPromotionSeckillRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_promotion_seckill_rule
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}