package org.jinyuanjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.jinyuanjava.litemall.db.domain.LitemallPrivateMakeRule;
import org.jinyuanjava.litemall.db.domain.LitemallPrivateMakeRuleExample;

public interface LitemallPrivateMakeRuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_private_make_rule
     *
     * @mbg.generated
     */
    long countByExample(LitemallPrivateMakeRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_private_make_rule
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallPrivateMakeRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_private_make_rule
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_private_make_rule
     *
     * @mbg.generated
     */
    int insert(LitemallPrivateMakeRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_private_make_rule
     *
     * @mbg.generated
     */
    int insertSelective(LitemallPrivateMakeRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_private_make_rule
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallPrivateMakeRule selectOneByExample(LitemallPrivateMakeRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_private_make_rule
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallPrivateMakeRule selectOneByExampleSelective(@Param("example") LitemallPrivateMakeRuleExample example, @Param("selective") LitemallPrivateMakeRule.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_private_make_rule
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallPrivateMakeRule> selectByExampleSelective(@Param("example") LitemallPrivateMakeRuleExample example, @Param("selective") LitemallPrivateMakeRule.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_private_make_rule
     *
     * @mbg.generated
     */
    List<LitemallPrivateMakeRule> selectByExample(LitemallPrivateMakeRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_private_make_rule
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallPrivateMakeRule selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallPrivateMakeRule.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_private_make_rule
     *
     * @mbg.generated
     */
    LitemallPrivateMakeRule selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_private_make_rule
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallPrivateMakeRule selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_private_make_rule
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallPrivateMakeRule record, @Param("example") LitemallPrivateMakeRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_private_make_rule
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallPrivateMakeRule record, @Param("example") LitemallPrivateMakeRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_private_make_rule
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallPrivateMakeRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_private_make_rule
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallPrivateMakeRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_private_make_rule
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") LitemallPrivateMakeRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_private_make_rule
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}