package org.jinyuanjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.jinyuanjava.litemall.db.domain.LitemallCompany;
import org.jinyuanjava.litemall.db.domain.LitemallCompanyExample;

public interface LitemallCompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_company
     *
     * @mbg.generated
     */
    long countByExample(LitemallCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_company
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_company
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_company
     *
     * @mbg.generated
     */
    int insert(LitemallCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_company
     *
     * @mbg.generated
     */
    int insertSelective(LitemallCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_company
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallCompany selectOneByExample(LitemallCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_company
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallCompany selectOneByExampleSelective(@Param("example") LitemallCompanyExample example, @Param("selective") LitemallCompany.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_company
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallCompany selectOneByExampleWithBLOBs(LitemallCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_company
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallCompany> selectByExampleSelective(@Param("example") LitemallCompanyExample example, @Param("selective") LitemallCompany.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_company
     *
     * @mbg.generated
     */
    List<LitemallCompany> selectByExampleWithBLOBs(LitemallCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_company
     *
     * @mbg.generated
     */
    List<LitemallCompany> selectByExample(LitemallCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_company
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallCompany selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallCompany.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_company
     *
     * @mbg.generated
     */
    LitemallCompany selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_company
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallCompany selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_company
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallCompany record, @Param("example") LitemallCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_company
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") LitemallCompany record, @Param("example") LitemallCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_company
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallCompany record, @Param("example") LitemallCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_company
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_company
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(LitemallCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_company
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_company
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") LitemallCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_company
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}