package org.jinyuanjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.jinyuanjava.litemall.db.domain.LitemallHomeBackgroundImage;
import org.jinyuanjava.litemall.db.domain.LitemallHomeBackgroundImageExample;

public interface LitemallHomeBackgroundImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_home_background_image
     *
     * @mbg.generated
     */
    long countByExample(LitemallHomeBackgroundImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_home_background_image
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallHomeBackgroundImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_home_background_image
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_home_background_image
     *
     * @mbg.generated
     */
    int insert(LitemallHomeBackgroundImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_home_background_image
     *
     * @mbg.generated
     */
    int insertSelective(LitemallHomeBackgroundImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_home_background_image
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallHomeBackgroundImage selectOneByExample(LitemallHomeBackgroundImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_home_background_image
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallHomeBackgroundImage selectOneByExampleSelective(@Param("example") LitemallHomeBackgroundImageExample example, @Param("selective") LitemallHomeBackgroundImage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_home_background_image
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallHomeBackgroundImage> selectByExampleSelective(@Param("example") LitemallHomeBackgroundImageExample example, @Param("selective") LitemallHomeBackgroundImage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_home_background_image
     *
     * @mbg.generated
     */
    List<LitemallHomeBackgroundImage> selectByExample(LitemallHomeBackgroundImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_home_background_image
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallHomeBackgroundImage selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallHomeBackgroundImage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_home_background_image
     *
     * @mbg.generated
     */
    LitemallHomeBackgroundImage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_home_background_image
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallHomeBackgroundImage selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_home_background_image
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallHomeBackgroundImage record, @Param("example") LitemallHomeBackgroundImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_home_background_image
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallHomeBackgroundImage record, @Param("example") LitemallHomeBackgroundImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_home_background_image
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallHomeBackgroundImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_home_background_image
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallHomeBackgroundImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_home_background_image
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") LitemallHomeBackgroundImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_home_background_image
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}