package org.jinyuanjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.jinyuanjava.litemall.db.domain.LitemallWeboguanRecommend;
import org.jinyuanjava.litemall.db.domain.LitemallWeboguanRecommendExample;

public interface LitemallWeboguanRecommendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_weboguan_recommend
     *
     * @mbg.generated
     */
    long countByExample(LitemallWeboguanRecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_weboguan_recommend
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallWeboguanRecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_weboguan_recommend
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_weboguan_recommend
     *
     * @mbg.generated
     */
    int insert(LitemallWeboguanRecommend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_weboguan_recommend
     *
     * @mbg.generated
     */
    int insertSelective(LitemallWeboguanRecommend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_weboguan_recommend
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallWeboguanRecommend selectOneByExample(LitemallWeboguanRecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_weboguan_recommend
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallWeboguanRecommend selectOneByExampleSelective(@Param("example") LitemallWeboguanRecommendExample example, @Param("selective") LitemallWeboguanRecommend.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_weboguan_recommend
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallWeboguanRecommend> selectByExampleSelective(@Param("example") LitemallWeboguanRecommendExample example, @Param("selective") LitemallWeboguanRecommend.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_weboguan_recommend
     *
     * @mbg.generated
     */
    List<LitemallWeboguanRecommend> selectByExample(LitemallWeboguanRecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_weboguan_recommend
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallWeboguanRecommend selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallWeboguanRecommend.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_weboguan_recommend
     *
     * @mbg.generated
     */
    LitemallWeboguanRecommend selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_weboguan_recommend
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallWeboguanRecommend selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_weboguan_recommend
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallWeboguanRecommend record, @Param("example") LitemallWeboguanRecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_weboguan_recommend
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallWeboguanRecommend record, @Param("example") LitemallWeboguanRecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_weboguan_recommend
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallWeboguanRecommend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_weboguan_recommend
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallWeboguanRecommend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_weboguan_recommend
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") LitemallWeboguanRecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_weboguan_recommend
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}