package org.jinyuanjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.jinyuanjava.litemall.db.domain.LitemallAuctionZhuanchangGoodsCurrent;
import org.jinyuanjava.litemall.db.domain.LitemallAuctionZhuanchangGoodsCurrentExample;

public interface LitemallAuctionZhuanchangGoodsCurrentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_auction_zhuanchang_goods_current
     *
     * @mbg.generated
     */
    long countByExample(LitemallAuctionZhuanchangGoodsCurrentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_auction_zhuanchang_goods_current
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallAuctionZhuanchangGoodsCurrentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_auction_zhuanchang_goods_current
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_auction_zhuanchang_goods_current
     *
     * @mbg.generated
     */
    int insert(LitemallAuctionZhuanchangGoodsCurrent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_auction_zhuanchang_goods_current
     *
     * @mbg.generated
     */
    int insertSelective(LitemallAuctionZhuanchangGoodsCurrent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_auction_zhuanchang_goods_current
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallAuctionZhuanchangGoodsCurrent selectOneByExample(LitemallAuctionZhuanchangGoodsCurrentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_auction_zhuanchang_goods_current
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallAuctionZhuanchangGoodsCurrent selectOneByExampleSelective(@Param("example") LitemallAuctionZhuanchangGoodsCurrentExample example, @Param("selective") LitemallAuctionZhuanchangGoodsCurrent.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_auction_zhuanchang_goods_current
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallAuctionZhuanchangGoodsCurrent> selectByExampleSelective(@Param("example") LitemallAuctionZhuanchangGoodsCurrentExample example, @Param("selective") LitemallAuctionZhuanchangGoodsCurrent.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_auction_zhuanchang_goods_current
     *
     * @mbg.generated
     */
    List<LitemallAuctionZhuanchangGoodsCurrent> selectByExample(LitemallAuctionZhuanchangGoodsCurrentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_auction_zhuanchang_goods_current
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallAuctionZhuanchangGoodsCurrent selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallAuctionZhuanchangGoodsCurrent.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_auction_zhuanchang_goods_current
     *
     * @mbg.generated
     */
    LitemallAuctionZhuanchangGoodsCurrent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_auction_zhuanchang_goods_current
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallAuctionZhuanchangGoodsCurrent selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_auction_zhuanchang_goods_current
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallAuctionZhuanchangGoodsCurrent record, @Param("example") LitemallAuctionZhuanchangGoodsCurrentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_auction_zhuanchang_goods_current
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallAuctionZhuanchangGoodsCurrent record, @Param("example") LitemallAuctionZhuanchangGoodsCurrentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_auction_zhuanchang_goods_current
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallAuctionZhuanchangGoodsCurrent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_auction_zhuanchang_goods_current
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallAuctionZhuanchangGoodsCurrent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_auction_zhuanchang_goods_current
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") LitemallAuctionZhuanchangGoodsCurrentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_auction_zhuanchang_goods_current
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}