package org.jinyuanjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.jinyuanjava.litemall.db.domain.LitemallHuodongMain;
import org.jinyuanjava.litemall.db.domain.LitemallHuodongMainExample;

public interface LitemallHuodongMainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_huodong_main
     *
     * @mbg.generated
     */
    long countByExample(LitemallHuodongMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_huodong_main
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallHuodongMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_huodong_main
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_huodong_main
     *
     * @mbg.generated
     */
    int insert(LitemallHuodongMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_huodong_main
     *
     * @mbg.generated
     */
    int insertSelective(LitemallHuodongMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_huodong_main
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallHuodongMain selectOneByExample(LitemallHuodongMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_huodong_main
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallHuodongMain selectOneByExampleSelective(@Param("example") LitemallHuodongMainExample example, @Param("selective") LitemallHuodongMain.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_huodong_main
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallHuodongMain> selectByExampleSelective(@Param("example") LitemallHuodongMainExample example, @Param("selective") LitemallHuodongMain.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_huodong_main
     *
     * @mbg.generated
     */
    List<LitemallHuodongMain> selectByExample(LitemallHuodongMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_huodong_main
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallHuodongMain selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallHuodongMain.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_huodong_main
     *
     * @mbg.generated
     */
    LitemallHuodongMain selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_huodong_main
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallHuodongMain selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_huodong_main
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallHuodongMain record, @Param("example") LitemallHuodongMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_huodong_main
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallHuodongMain record, @Param("example") LitemallHuodongMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_huodong_main
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallHuodongMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_huodong_main
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallHuodongMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_huodong_main
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") LitemallHuodongMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_huodong_main
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}