package org.jinyuanjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.jinyuanjava.litemall.db.domain.ViewListRecommendGroupon;
import org.jinyuanjava.litemall.db.domain.ViewListRecommendGrouponExample;
import org.jinyuanjava.litemall.db.domain.ViewListRecommendGrouponWithBLOBs;

public interface ViewListRecommendGrouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_list_recommend_groupon
     *
     * @mbg.generated
     */
    long countByExample(ViewListRecommendGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_list_recommend_groupon
     *
     * @mbg.generated
     */
    int deleteByExample(ViewListRecommendGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_list_recommend_groupon
     *
     * @mbg.generated
     */
    int insert(ViewListRecommendGrouponWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_list_recommend_groupon
     *
     * @mbg.generated
     */
    int insertSelective(ViewListRecommendGrouponWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_list_recommend_groupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ViewListRecommendGroupon selectOneByExample(ViewListRecommendGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_list_recommend_groupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ViewListRecommendGrouponWithBLOBs selectOneByExampleSelective(@Param("example") ViewListRecommendGrouponExample example, @Param("selective") ViewListRecommendGrouponWithBLOBs.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_list_recommend_groupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ViewListRecommendGrouponWithBLOBs selectOneByExampleWithBLOBs(ViewListRecommendGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_list_recommend_groupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ViewListRecommendGrouponWithBLOBs> selectByExampleSelective(@Param("example") ViewListRecommendGrouponExample example, @Param("selective") ViewListRecommendGrouponWithBLOBs.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_list_recommend_groupon
     *
     * @mbg.generated
     */
    List<ViewListRecommendGrouponWithBLOBs> selectByExampleWithBLOBs(ViewListRecommendGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_list_recommend_groupon
     *
     * @mbg.generated
     */
    List<ViewListRecommendGroupon> selectByExample(ViewListRecommendGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_list_recommend_groupon
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ViewListRecommendGrouponWithBLOBs record, @Param("example") ViewListRecommendGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_list_recommend_groupon
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") ViewListRecommendGrouponWithBLOBs record, @Param("example") ViewListRecommendGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_list_recommend_groupon
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ViewListRecommendGroupon record, @Param("example") ViewListRecommendGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_list_recommend_groupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ViewListRecommendGrouponExample example);
}