package org.jinyuanjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.jinyuanjava.litemall.db.domain.ViewHomepageRecommendGroupon;
import org.jinyuanjava.litemall.db.domain.ViewHomepageRecommendGrouponExample;
import org.jinyuanjava.litemall.db.domain.ViewHomepageRecommendGrouponWithBLOBs;

public interface ViewHomepageRecommendGrouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_homepage_recommend_groupon
     *
     * @mbg.generated
     */
    long countByExample(ViewHomepageRecommendGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_homepage_recommend_groupon
     *
     * @mbg.generated
     */
    int deleteByExample(ViewHomepageRecommendGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_homepage_recommend_groupon
     *
     * @mbg.generated
     */
    int insert(ViewHomepageRecommendGrouponWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_homepage_recommend_groupon
     *
     * @mbg.generated
     */
    int insertSelective(ViewHomepageRecommendGrouponWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_homepage_recommend_groupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ViewHomepageRecommendGroupon selectOneByExample(ViewHomepageRecommendGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_homepage_recommend_groupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ViewHomepageRecommendGrouponWithBLOBs selectOneByExampleSelective(@Param("example") ViewHomepageRecommendGrouponExample example, @Param("selective") ViewHomepageRecommendGrouponWithBLOBs.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_homepage_recommend_groupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ViewHomepageRecommendGrouponWithBLOBs selectOneByExampleWithBLOBs(ViewHomepageRecommendGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_homepage_recommend_groupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ViewHomepageRecommendGrouponWithBLOBs> selectByExampleSelective(@Param("example") ViewHomepageRecommendGrouponExample example, @Param("selective") ViewHomepageRecommendGrouponWithBLOBs.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_homepage_recommend_groupon
     *
     * @mbg.generated
     */
    List<ViewHomepageRecommendGrouponWithBLOBs> selectByExampleWithBLOBs(ViewHomepageRecommendGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_homepage_recommend_groupon
     *
     * @mbg.generated
     */
    List<ViewHomepageRecommendGroupon> selectByExample(ViewHomepageRecommendGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_homepage_recommend_groupon
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ViewHomepageRecommendGrouponWithBLOBs record, @Param("example") ViewHomepageRecommendGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_homepage_recommend_groupon
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") ViewHomepageRecommendGrouponWithBLOBs record, @Param("example") ViewHomepageRecommendGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_homepage_recommend_groupon
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ViewHomepageRecommendGroupon record, @Param("example") ViewHomepageRecommendGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_homepage_recommend_groupon
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ViewHomepageRecommendGrouponExample example);
}