package org.jinyuanjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.jinyuanjava.litemall.db.domain.ViewUserGoodsOrders;
import org.jinyuanjava.litemall.db.domain.ViewUserGoodsOrdersExample;

public interface ViewUserGoodsOrdersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_user_goods_orders
     *
     * @mbg.generated
     */
    long countByExample(ViewUserGoodsOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_user_goods_orders
     *
     * @mbg.generated
     */
    int deleteByExample(ViewUserGoodsOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_user_goods_orders
     *
     * @mbg.generated
     */
    int insert(ViewUserGoodsOrders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_user_goods_orders
     *
     * @mbg.generated
     */
    int insertSelective(ViewUserGoodsOrders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_user_goods_orders
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ViewUserGoodsOrders selectOneByExample(ViewUserGoodsOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_user_goods_orders
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ViewUserGoodsOrders selectOneByExampleSelective(@Param("example") ViewUserGoodsOrdersExample example, @Param("selective") ViewUserGoodsOrders.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_user_goods_orders
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ViewUserGoodsOrders> selectByExampleSelective(@Param("example") ViewUserGoodsOrdersExample example, @Param("selective") ViewUserGoodsOrders.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_user_goods_orders
     *
     * @mbg.generated
     */
    List<ViewUserGoodsOrders> selectByExample(ViewUserGoodsOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_user_goods_orders
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ViewUserGoodsOrders record, @Param("example") ViewUserGoodsOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_user_goods_orders
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ViewUserGoodsOrders record, @Param("example") ViewUserGoodsOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_user_goods_orders
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ViewUserGoodsOrdersExample example);
}