package org.jinyuanjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.jinyuanjava.litemall.db.domain.ViewAuctionDajiaOfferCurrent;
import org.jinyuanjava.litemall.db.domain.ViewAuctionDajiaOfferCurrentExample;

public interface ViewAuctionDajiaOfferCurrentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_auction_dajia_offer_current
     *
     * @mbg.generated
     */
    long countByExample(ViewAuctionDajiaOfferCurrentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_auction_dajia_offer_current
     *
     * @mbg.generated
     */
    int deleteByExample(ViewAuctionDajiaOfferCurrentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_auction_dajia_offer_current
     *
     * @mbg.generated
     */
    int insert(ViewAuctionDajiaOfferCurrent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_auction_dajia_offer_current
     *
     * @mbg.generated
     */
    int insertSelective(ViewAuctionDajiaOfferCurrent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_auction_dajia_offer_current
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ViewAuctionDajiaOfferCurrent selectOneByExample(ViewAuctionDajiaOfferCurrentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_auction_dajia_offer_current
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ViewAuctionDajiaOfferCurrent selectOneByExampleSelective(@Param("example") ViewAuctionDajiaOfferCurrentExample example, @Param("selective") ViewAuctionDajiaOfferCurrent.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_auction_dajia_offer_current
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ViewAuctionDajiaOfferCurrent> selectByExampleSelective(@Param("example") ViewAuctionDajiaOfferCurrentExample example, @Param("selective") ViewAuctionDajiaOfferCurrent.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_auction_dajia_offer_current
     *
     * @mbg.generated
     */
    List<ViewAuctionDajiaOfferCurrent> selectByExample(ViewAuctionDajiaOfferCurrentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_auction_dajia_offer_current
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ViewAuctionDajiaOfferCurrent record, @Param("example") ViewAuctionDajiaOfferCurrentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_auction_dajia_offer_current
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ViewAuctionDajiaOfferCurrent record, @Param("example") ViewAuctionDajiaOfferCurrentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_auction_dajia_offer_current
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ViewAuctionDajiaOfferCurrentExample example);
}