package org.jinyuanjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.jinyuanjava.litemall.db.domain.ViewListPrivateMake;
import org.jinyuanjava.litemall.db.domain.ViewListPrivateMakeExample;
import org.jinyuanjava.litemall.db.domain.ViewListPrivateMakeWithBLOBs;

public interface ViewListPrivateMakeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_list_private_make
     *
     * @mbg.generated
     */
    long countByExample(ViewListPrivateMakeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_list_private_make
     *
     * @mbg.generated
     */
    int deleteByExample(ViewListPrivateMakeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_list_private_make
     *
     * @mbg.generated
     */
    int insert(ViewListPrivateMakeWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_list_private_make
     *
     * @mbg.generated
     */
    int insertSelective(ViewListPrivateMakeWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_list_private_make
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ViewListPrivateMake selectOneByExample(ViewListPrivateMakeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_list_private_make
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ViewListPrivateMakeWithBLOBs selectOneByExampleSelective(@Param("example") ViewListPrivateMakeExample example, @Param("selective") ViewListPrivateMakeWithBLOBs.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_list_private_make
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ViewListPrivateMakeWithBLOBs selectOneByExampleWithBLOBs(ViewListPrivateMakeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_list_private_make
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ViewListPrivateMakeWithBLOBs> selectByExampleSelective(@Param("example") ViewListPrivateMakeExample example, @Param("selective") ViewListPrivateMakeWithBLOBs.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_list_private_make
     *
     * @mbg.generated
     */
    List<ViewListPrivateMakeWithBLOBs> selectByExampleWithBLOBs(ViewListPrivateMakeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_list_private_make
     *
     * @mbg.generated
     */
    List<ViewListPrivateMake> selectByExample(ViewListPrivateMakeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_list_private_make
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ViewListPrivateMakeWithBLOBs record, @Param("example") ViewListPrivateMakeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_list_private_make
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") ViewListPrivateMakeWithBLOBs record, @Param("example") ViewListPrivateMakeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_list_private_make
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ViewListPrivateMake record, @Param("example") ViewListPrivateMakeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_list_private_make
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ViewListPrivateMakeExample example);
}
