package org.jinyuanjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.jinyuanjava.litemall.db.domain.ViewListRecommendSeckill;
import org.jinyuanjava.litemall.db.domain.ViewListRecommendSeckillExample;
import org.jinyuanjava.litemall.db.domain.ViewListRecommendSeckillWithBLOBs;

public interface ViewListRecommendSeckillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_list_recommend_seckill
     *
     * @mbg.generated
     */
    long countByExample(ViewListRecommendSeckillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_list_recommend_seckill
     *
     * @mbg.generated
     */
    int deleteByExample(ViewListRecommendSeckillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_list_recommend_seckill
     *
     * @mbg.generated
     */
    int insert(ViewListRecommendSeckillWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_list_recommend_seckill
     *
     * @mbg.generated
     */
    int insertSelective(ViewListRecommendSeckillWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_list_recommend_seckill
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ViewListRecommendSeckill selectOneByExample(ViewListRecommendSeckillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_list_recommend_seckill
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ViewListRecommendSeckillWithBLOBs selectOneByExampleSelective(@Param("example") ViewListRecommendSeckillExample example, @Param("selective") ViewListRecommendSeckillWithBLOBs.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_list_recommend_seckill
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ViewListRecommendSeckillWithBLOBs selectOneByExampleWithBLOBs(ViewListRecommendSeckillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_list_recommend_seckill
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ViewListRecommendSeckillWithBLOBs> selectByExampleSelective(@Param("example") ViewListRecommendSeckillExample example, @Param("selective") ViewListRecommendSeckillWithBLOBs.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_list_recommend_seckill
     *
     * @mbg.generated
     */
    List<ViewListRecommendSeckillWithBLOBs> selectByExampleWithBLOBs(ViewListRecommendSeckillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_list_recommend_seckill
     *
     * @mbg.generated
     */
    List<ViewListRecommendSeckill> selectByExample(ViewListRecommendSeckillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_list_recommend_seckill
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ViewListRecommendSeckillWithBLOBs record, @Param("example") ViewListRecommendSeckillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_list_recommend_seckill
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") ViewListRecommendSeckillWithBLOBs record, @Param("example") ViewListRecommendSeckillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_list_recommend_seckill
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ViewListRecommendSeckill record, @Param("example") ViewListRecommendSeckillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_list_recommend_seckill
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ViewListRecommendSeckillExample example);
}