package org.jinyuanjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.jinyuanjava.litemall.db.domain.ViewSeckillOrders;
import org.jinyuanjava.litemall.db.domain.ViewSeckillOrdersExample;

public interface ViewSeckillOrdersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_seckill_orders
     *
     * @mbg.generated
     */
    long countByExample(ViewSeckillOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_seckill_orders
     *
     * @mbg.generated
     */
    int deleteByExample(ViewSeckillOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_seckill_orders
     *
     * @mbg.generated
     */
    int insert(ViewSeckillOrders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_seckill_orders
     *
     * @mbg.generated
     */
    int insertSelective(ViewSeckillOrders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_seckill_orders
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ViewSeckillOrders selectOneByExample(ViewSeckillOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_seckill_orders
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ViewSeckillOrders selectOneByExampleSelective(@Param("example") ViewSeckillOrdersExample example, @Param("selective") ViewSeckillOrders.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_seckill_orders
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ViewSeckillOrders> selectByExampleSelective(@Param("example") ViewSeckillOrdersExample example, @Param("selective") ViewSeckillOrders.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_seckill_orders
     *
     * @mbg.generated
     */
    List<ViewSeckillOrders> selectByExample(ViewSeckillOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_seckill_orders
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ViewSeckillOrders record, @Param("example") ViewSeckillOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_seckill_orders
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ViewSeckillOrders record, @Param("example") ViewSeckillOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_seckill_orders
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ViewSeckillOrdersExample example);
}