package org.jinyuanjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.jinyuanjava.litemall.db.domain.ViewLitemallGoodsRecommend;
import org.jinyuanjava.litemall.db.domain.ViewLitemallGoodsRecommendExample;

public interface ViewLitemallGoodsRecommendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_litemall_goods_recommend
     *
     * @mbg.generated
     */
    long countByExample(ViewLitemallGoodsRecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_litemall_goods_recommend
     *
     * @mbg.generated
     */
    int deleteByExample(ViewLitemallGoodsRecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_litemall_goods_recommend
     *
     * @mbg.generated
     */
    int insert(ViewLitemallGoodsRecommend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_litemall_goods_recommend
     *
     * @mbg.generated
     */
    int insertSelective(ViewLitemallGoodsRecommend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_litemall_goods_recommend
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ViewLitemallGoodsRecommend selectOneByExample(ViewLitemallGoodsRecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_litemall_goods_recommend
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ViewLitemallGoodsRecommend selectOneByExampleSelective(@Param("example") ViewLitemallGoodsRecommendExample example, @Param("selective") ViewLitemallGoodsRecommend.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_litemall_goods_recommend
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ViewLitemallGoodsRecommend selectOneByExampleWithBLOBs(ViewLitemallGoodsRecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_litemall_goods_recommend
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ViewLitemallGoodsRecommend> selectByExampleSelective(@Param("example") ViewLitemallGoodsRecommendExample example, @Param("selective") ViewLitemallGoodsRecommend.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_litemall_goods_recommend
     *
     * @mbg.generated
     */
    List<ViewLitemallGoodsRecommend> selectByExampleWithBLOBs(ViewLitemallGoodsRecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_litemall_goods_recommend
     *
     * @mbg.generated
     */
    List<ViewLitemallGoodsRecommend> selectByExample(ViewLitemallGoodsRecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_litemall_goods_recommend
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ViewLitemallGoodsRecommend record, @Param("example") ViewLitemallGoodsRecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_litemall_goods_recommend
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") ViewLitemallGoodsRecommend record, @Param("example") ViewLitemallGoodsRecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_litemall_goods_recommend
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ViewLitemallGoodsRecommend record, @Param("example") ViewLitemallGoodsRecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_litemall_goods_recommend
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ViewLitemallGoodsRecommendExample example);
}