package org.jinyuanjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.jinyuanjava.litemall.db.domain.ViewPrivateMakeOrder;
import org.jinyuanjava.litemall.db.domain.ViewPrivateMakeOrderExample;

public interface ViewPrivateMakeOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_private_make_order
     *
     * @mbg.generated
     */
    long countByExample(ViewPrivateMakeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_private_make_order
     *
     * @mbg.generated
     */
    int deleteByExample(ViewPrivateMakeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_private_make_order
     *
     * @mbg.generated
     */
    int insert(ViewPrivateMakeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_private_make_order
     *
     * @mbg.generated
     */
    int insertSelective(ViewPrivateMakeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_private_make_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ViewPrivateMakeOrder selectOneByExample(ViewPrivateMakeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_private_make_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ViewPrivateMakeOrder selectOneByExampleSelective(@Param("example") ViewPrivateMakeOrderExample example, @Param("selective") ViewPrivateMakeOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_private_make_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ViewPrivateMakeOrder> selectByExampleSelective(@Param("example") ViewPrivateMakeOrderExample example, @Param("selective") ViewPrivateMakeOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_private_make_order
     *
     * @mbg.generated
     */
    List<ViewPrivateMakeOrder> selectByExample(ViewPrivateMakeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_private_make_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ViewPrivateMakeOrder record, @Param("example") ViewPrivateMakeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_private_make_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ViewPrivateMakeOrder record, @Param("example") ViewPrivateMakeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_private_make_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ViewPrivateMakeOrderExample example);
}