package org.jinyuanjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.jinyuanjava.litemall.db.domain.ViewGrouponOrders;
import org.jinyuanjava.litemall.db.domain.ViewGrouponOrdersExample;

public interface ViewGrouponOrdersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_groupon_orders
     *
     * @mbg.generated
     */
    long countByExample(ViewGrouponOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_groupon_orders
     *
     * @mbg.generated
     */
    int deleteByExample(ViewGrouponOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_groupon_orders
     *
     * @mbg.generated
     */
    int insert(ViewGrouponOrders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_groupon_orders
     *
     * @mbg.generated
     */
    int insertSelective(ViewGrouponOrders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_groupon_orders
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ViewGrouponOrders selectOneByExample(ViewGrouponOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_groupon_orders
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ViewGrouponOrders selectOneByExampleSelective(@Param("example") ViewGrouponOrdersExample example, @Param("selective") ViewGrouponOrders.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_groupon_orders
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ViewGrouponOrders> selectByExampleSelective(@Param("example") ViewGrouponOrdersExample example, @Param("selective") ViewGrouponOrders.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_groupon_orders
     *
     * @mbg.generated
     */
    List<ViewGrouponOrders> selectByExample(ViewGrouponOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_groupon_orders
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ViewGrouponOrders record, @Param("example") ViewGrouponOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_groupon_orders
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ViewGrouponOrders record, @Param("example") ViewGrouponOrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_groupon_orders
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ViewGrouponOrdersExample example);
}