package org.jinyuanjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.jinyuanjava.litemall.db.domain.ViewAuctionZhuanchangOfferCurrent;
import org.jinyuanjava.litemall.db.domain.ViewAuctionZhuanchangOfferCurrentExample;

public interface ViewAuctionZhuanchangOfferCurrentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_auction_zhuanchang_offer_current
     *
     * @mbg.generated
     */
    long countByExample(ViewAuctionZhuanchangOfferCurrentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_auction_zhuanchang_offer_current
     *
     * @mbg.generated
     */
    int deleteByExample(ViewAuctionZhuanchangOfferCurrentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_auction_zhuanchang_offer_current
     *
     * @mbg.generated
     */
    int insert(ViewAuctionZhuanchangOfferCurrent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_auction_zhuanchang_offer_current
     *
     * @mbg.generated
     */
    int insertSelective(ViewAuctionZhuanchangOfferCurrent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_auction_zhuanchang_offer_current
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ViewAuctionZhuanchangOfferCurrent selectOneByExample(ViewAuctionZhuanchangOfferCurrentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_auction_zhuanchang_offer_current
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ViewAuctionZhuanchangOfferCurrent selectOneByExampleSelective(@Param("example") ViewAuctionZhuanchangOfferCurrentExample example, @Param("selective") ViewAuctionZhuanchangOfferCurrent.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_auction_zhuanchang_offer_current
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ViewAuctionZhuanchangOfferCurrent> selectByExampleSelective(@Param("example") ViewAuctionZhuanchangOfferCurrentExample example, @Param("selective") ViewAuctionZhuanchangOfferCurrent.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_auction_zhuanchang_offer_current
     *
     * @mbg.generated
     */
    List<ViewAuctionZhuanchangOfferCurrent> selectByExample(ViewAuctionZhuanchangOfferCurrentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_auction_zhuanchang_offer_current
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ViewAuctionZhuanchangOfferCurrent record, @Param("example") ViewAuctionZhuanchangOfferCurrentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_auction_zhuanchang_offer_current
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ViewAuctionZhuanchangOfferCurrent record, @Param("example") ViewAuctionZhuanchangOfferCurrentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_auction_zhuanchang_offer_current
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ViewAuctionZhuanchangOfferCurrentExample example);
}